on:
  issues:
    types:
      - opened
      - edited

jobs:
    auto_close_issues:
        runs-on: self-hosted
        steps:
            - name: Check out Git repository
              uses: actions/checkout@v3

            - name: Automatically close issues that don't follow the issue template
              uses: ergo720/auto-close-issues@v1.0.4
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                issue-close-message: "Closing this issue since the issue template was not filled in. Please provide us with more information to have this issue reopened." # optional property
                closed-issues-label: "invalid"