name: Close stale issues and PRs
on:
  schedule:
    - cron: 30 1 * * *
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          exempt-pr-labels: dependencies,review-required
          exempt-issue-labels: enhancement
permissions:
  issues: write
  pull-requests: write
